### ISSUE TITLE
Игра с модом Wynntils

### ISSUE THREAD

**Issue by Suiranoil** [ArtFect/WynnLang#3]
При игре с модом Wynntils переводятся не все строки

Пример 1(1 скрин с Wynntils; 2 - без)
![Screenshot_1](https://user-images.githubusercontent.com/45388086/81799663-59698f80-951a-11ea-8775-4dc90ffb3d1d.png)
![Screenshot_4](https://user-images.githubusercontent.com/45388086/81799670-5bcbe980-951a-11ea-9364-80f7e5fbe235.png)

Пример 2(1 скрин с Wynntils; 2 - без)
![Screenshot_2](https://user-images.githubusercontent.com/45388086/81799759-7900b800-951a-11ea-93df-ebd654488047.png)
![Screenshot_5](https://user-images.githubusercontent.com/45388086/81799769-7bfba880-951a-11ea-9b44-bde9a6faf731.png)

Пример 3(1 скрин с Wynntils; 2 - без)
![Screenshot_3](https://user-images.githubusercontent.com/45388086/81799903-b2392800-951a-11ea-9282-f5e2ced5f460.png)
![Screenshot_6](https://user-images.githubusercontent.com/45388086/81799914-b5341880-951a-11ea-9b61-879a33758e6e.png)

**Comment by ArtFect** [comment]
Мы специально отключили перевод некоторых строк при установленном моде wynntils
Если это не сделать, то сломается практически весь его функционал
